import { spawn } from "node:child_process"
import crypto from "node:crypto"
import fs from "node:fs"
import path from "node:path"

const contentExtensions = new Set([".html", ".liquid", ".md"])
const ignoredDirs = new Set([".git", "_site", "docs", "node_modules"])
const ignoredFiles = new Set(["CHANGELOG.md", "README.md"])

export function collectContentFiles(dir) {
  const files = []

  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (!ignoredDirs.has(entry.name)) {
        files.push(...collectContentFiles(path.join(dir, entry.name)))
      }
      continue
    }

    if (entry.isFile() && contentExtensions.has(path.extname(entry.name)) && !ignoredFiles.has(entry.name)) {
      files.push(path.join(dir, entry.name))
    }
  }

  return files
}

export function parseS3AssetIncludes(file, contents) {
  const includes = []
  const tagPattern = /{%-?\s*include\s+s3_asset\.html\s+([\s\S]*?)-?%}/g
  let tagMatch

  while ((tagMatch = tagPattern.exec(contents))) {
    const attrs = {}
    const attrPattern = /([A-Za-z0-9_-]+)\s*=\s*("[^"]*"|'[^']*'|[^\s%]+)/g
    let attrMatch
    let pathIsQuoted = false

    while ((attrMatch = attrPattern.exec(tagMatch[1]))) {
      const value = attrMatch[2]
      const isQuoted = (value.startsWith("'") && value.endsWith("'")) || (value.startsWith('"') && value.endsWith('"'))

      if (attrMatch[1] === "path" && isQuoted) {
        pathIsQuoted = true
      }

      attrs[attrMatch[1]] = parseIncludeValue(value)
    }

    if (!pathIsQuoted || typeof attrs.path !== "string" || attrs.path === "" || /[{%}]/.test(attrs.path)) {
      throw new Error(`Cannot statically resolve s3_asset path in ${file}: ${tagMatch[0].trim()}`)
    }

    includes.push({ bundle: attrs.bundle === true || attrs.bundle === "true", file, path: attrs.path })
  }

  return includes
}

export function discoverS3Assets(root) {
  return collectContentFiles(root).flatMap(file =>
    parseS3AssetIncludes(path.relative(root, file), fs.readFileSync(file, "utf8"))
  )
}

export function resolveS3Path(assetPath, bundle, bundlePrefix) {
  if (bundle && bundlePrefix) {
    return assetPath.replaceAll("/bundle", `/${bundlePrefix}bundle`)
  }

  return assetPath
}

export function objectKeyFromS3Path(s3Path) {
  return s3Path.split("#", 1)[0].split("?", 1)[0].replace(/^\/+/, "")
}

export function versionFromMetadata(metadata) {
  if (metadata.VersionId && metadata.VersionId !== "null") {
    return { source: "s3_version_id", version: normalizeVersion(metadata.VersionId) }
  }

  if (metadata.ETag) {
    return { source: "s3_etag", version: normalizeVersion(metadata.ETag.replace(/^"|"$/g, "")) }
  }

  if (metadata.LastModified && metadata.ContentLength !== undefined) {
    return {
      source: "s3_last_modified_content_length",
      version: normalizeVersion(`${metadata.LastModified}-${metadata.ContentLength}`)
    }
  }

  throw new Error("S3 metadata did not include VersionId, ETag, or LastModified plus ContentLength")
}

export function fallbackVersion(key) {
  return `local-${crypto.createHash("sha256").update(key).digest("hex").slice(0, 16)}`
}

export async function buildS3AssetEntries({ bundlePrefix = "", headObject, mode = "fallback", root = process.cwd() }) {
  const keys = new Set()

  for (const asset of discoverS3Assets(root)) {
    const key = objectKeyFromS3Path(resolveS3Path(asset.path, asset.bundle, bundlePrefix))

    if (!key) {
      throw new Error(`Resolved an empty S3 object key for ${asset.file}: ${asset.path}`)
    }

    keys.add(key)
  }

  const entries = []

  for (const key of [...keys].sort()) {
    if (mode === "fallback") {
      entries.push({ key, logicalId: logicalIdForKey(key), source: "local_fallback", version: fallbackVersion(key) })
      continue
    }

    const { source, version } = versionFromMetadata(await headObject(key))
    entries.push({ key, logicalId: logicalIdForKey(key), source, version })
  }

  return entries
}

export function writeS3AssetData(outFile, entries) {
  const lines = [
    "# Generated by scripts/generate-s3-asset-versions.mjs. Do not edit by hand.",
    "# Refresh with: npm run update:s3-assets"
  ]

  for (const entry of entries) {
    lines.push("- logical_id: " + yamlQuote(entry.logicalId))
    lines.push(`  key: ${yamlQuote(entry.key)}`)
    lines.push(`  source: ${yamlQuote(entry.source)}`)
    lines.push(`  version: ${yamlQuote(entry.version)}`)
  }

  fs.mkdirSync(path.dirname(outFile), { recursive: true })
  fs.writeFileSync(outFile, `${lines.join("\n")}\n`)
}

export function readSiteS3Config(root) {
  const config = {}

  for (const line of fs.readFileSync(path.join(root, "_config.yml"), "utf8").split("\n")) {
    const match = line.match(/^(s3_bucket|s3_bundle_prefix):\s*(.*?)\s*$/)

    if (match) {
      config[match[1]] = match[2].replace(/^['"]|['"]$/g, "")
    }
  }

  return {
    bucket: bucketNameFromSiteValue(config.s3_bucket),
    bundlePrefix: config.s3_bundle_prefix || "",
    region: regionFromSiteValue(config.s3_bucket)
  }
}

export function headS3Object({ bucket, key, profile, region }) {
  const args = ["s3api", "head-object", "--bucket", bucket, "--key", key, "--output", "json"]

  if (region) {
    args.push("--region", region)
  }

  if (profile) {
    args.push("--profile", profile)
  }

  return new Promise((resolve, reject) => {
    const child = spawn("aws", args, { stdio: ["ignore", "pipe", "pipe"] })
    let stdout = ""
    let stderr = ""

    child.stdout.setEncoding("utf8")
    child.stdout.on("data", chunk => {
      stdout += chunk
    })

    child.stderr.setEncoding("utf8")
    child.stderr.on("data", chunk => {
      stderr += chunk
    })

    child.on("error", reject)
    child.on("close", code => {
      if (code !== 0) {
        reject(new Error(`Failed to read S3 metadata for ${key}: ${stderr.trim() || `aws exited with ${code}`}`))
        return
      }

      try {
        resolve(JSON.parse(stdout))
      } catch (error) {
        reject(new Error(`AWS returned invalid JSON for ${key}: ${error.message}`))
      }
    })
  })
}

function parseIncludeValue(value) {
  if ((value.startsWith("'") && value.endsWith("'")) || (value.startsWith('"') && value.endsWith('"'))) {
    return value.slice(1, -1)
  }

  if (value === "true") {
    return true
  }

  if (value === "false") {
    return false
  }

  return value
}

function logicalIdForKey(key) {
  return key
    .replace(/\.[^.]+$/, "")
    .replace(/[^A-Za-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toLowerCase()
}

function normalizeVersion(value) {
  return encodeURIComponent(String(value).trim())
}

function yamlQuote(value) {
  return `"${String(value).replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`
}

function bucketNameFromSiteValue(value) {
  if (!value) {
    return ""
  }

  const parsed = new URL(value)

  if (parsed.hostname.startsWith("s3.") && parsed.pathname !== "/") {
    return parsed.pathname.replace(/^\/+/, "").split("/")[0]
  }

  if (parsed.hostname.includes(".s3.")) {
    return parsed.hostname.split(".s3.")[0]
  }

  return parsed.hostname
}

function regionFromSiteValue(value) {
  if (!value) {
    return "us-east-2"
  }

  const match = new URL(value).hostname.match(/^s3[.-]([a-z0-9-]+)\.amazonaws\.com$/)

  return match ? match[1] : "us-east-2"
}
