name: Beautiful Jekyll CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build Jekyll
    uses: cyaris/svelte-lib/.github/workflows/jekyll-site-ci.yml@cy_dev3
    with:
      metadata-command: node scripts/update-github-repo-dates.mjs
