name: Beautiful Jekyll CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build Jekyll
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: "3.3"
      - name: Install dependencies
        run: bundle install && bundle exec appraisal install
      - name: Setup Pages
        id: configure-pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5
      - name: Setup CI config
        run: |
          echo "---" > _config_ci.yml
          echo "baseurl: ${{ steps.configure-pages.outputs.base_path }}" >> _config_ci.yml
      - name: Generate GitHub repository metadata
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: node scripts/update-github-repo-dates.mjs
      - name: Build site
        env:
          JEKYLL_ENV: production
        run: bundle exec appraisal jekyll build --future --config _config_ci.yml,_config.yml
      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3

  deploy:
    name: Deploy GitHub Pages
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    concurrency:
      group: pages
      cancel-in-progress: false
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy site
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
